# Generated by Django 5.2.6 on 2025-09-21 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(help_text='order_id from CSV', unique=True)),
                ('ordered_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('ingredients', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='PizzaVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XL'), ('XXL', 'XXL')], db_index=True, max_length=3)),
                ('slug', models.SlugField(help_text='pizza_name_id from CSV (e.g., hawaiian_m)', max_length=100, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='sales.pizza')),
            ],
            options={
                'ordering': ['pizza__name', 'size'],
                'unique_together': {('pizza', 'size')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_line_id', models.IntegerField(help_text='pizza_id from CSV (unique line id)', unique=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='sales.pizzavariant')),
            ],
            options={
                'ordering': ['order__ordered_at', 'id'],
            },
        ),
    ]
