# Generated by Django 5.2.6 on 2025-09-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='source_line_id',
            field=models.IntegerField(blank=True, help_text='pizza_id from CSV (unique line id); null for web orders', null=True, unique=True),
        ),
    ]
